### ISSUE TITLE
Tutorial: interfaces

### ISSUE THREAD

**Issue by OlingCat** [Idris-zh/Idris-dev#1]
- [x] 初译
- [x] 润色
- [x] 初校
- [x] 二校
- [x] 终稿

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L27

类型类（Typeclass）
特性（trait）

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L39

```
- 这会生成一个以下类型的函数（我们称其为 ``Show`` 接口的 **方法（Method）** ）：
+ 这会生成一个以下类型的函数，我们称其为 ``Show`` 接口的 **方法（Method）** ：
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L51

```
- 接口是通过定义接口的方法来实现的。
+ 我们可以通过定义接口的方法来实现一个接口。
```

这句话有点拗口，可能还是需要再修改一下？

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L74

```
- 一个类型只能被赋予某个接口的一个实现，即，实现无法被覆盖。
+ 一个类型只能被赋予某个接口的一个实现，即实现无法相互重叠。（？）
```

```
- 为此，实现的参数必须是构造器（即数据或类型构造器）或变量（即，无法为函数赋予实现）。
+ 为此，实现的参数必须是构造器（即数据或类型构造器）或变量（即无法为函数赋予实现）。
```

Re: 确实是覆盖，就是实现一次后就不能再实现一次了。

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L109

```
- 要为类型声明声明实现，我们必须给出所有方法的定义。例如，为 ``Nat`` 实现 ``Eq``：
+ 要声明类型实现了一个接口，我们必须给出所有方法的定义。例如，为 ``Nat`` 实现 ``Eq``：
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L127

```
- 因此，为接口声明中的每个方法提供默认定义会很方便，对其它方法而言：
+ 因此，用其他的方法为接口声明中的每个方法提供默认定义会很方便。
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L217

```
- Idris 是严格的「使用前先定义」，除了在 ``mutual`` 块中。
+ 除了在 ``mutual`` 块中，Idris 实行严格的「使用前先定义」。
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L348

速错原则（fail-fast）

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L482

```
- 然而需要注意，仅从语法上来说，它并不是一个真的函数！
+ 然而需要注意，它并不是一个真的函数，而是一个语法！
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L484

```
- 首先表达式的深度会按从左到右的顺序上升。
+ 首先表达式会按从左到右的顺序深度优先地上升。
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L485

```
- 同时仍能通过记法线索来标出单子性单子性的表达式。
+ 同时仍能通过记法线索来标出单子性的表达式。
```

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/interfaces.rst#L761

```
- 它正常地声明了一个实现
+ 它如同往常地声明了一个实现
```
