### ISSUE TITLE
Tutorial: theorems

### ISSUE THREAD

**Issue by OlingCat** [Idris-zh/Idris-dev#14]
- [x] 初译
- [x] 润色
- [x] 初校
- [x] 二校
- [x] 终稿

**Comment by OlingCat** [comment]
这一章实在不好翻译，求各位审校QAQ
@be5invis @duobei @fangyi-zhou @luochen1990 @zypeh @Z-Shang 
http://idris-zh.readthedocs.io/zh_CN/latest/tutorial/theorems.html

**Comment by duobei** [comment]
@OlingCat 今天下午有时间 过一下

**Comment by luochen1990** [comment]
LGTM
