### ISSUE TITLE
Tutorial: modules 

### ISSUE THREAD

**Issue by duobei** [Idris-zh/Idris-dev#2]
- [x] 初译
- [x] 润色
- [x] 初校
- [x] 二校
- [x] 终稿

**Comment by OlingCat** [comment]
modules 初校完毕，见 https://github.com/Idris-zh/Idris-dev/commit/7107cc322385cea9c5f295d5fcee6f01313b0fe9

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/modules.rst#L127

Remove empty bullet points

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/modules.rst#L157

```
- ``export`` 的类型是导出的
+ ``export`` ：导出类型
- ``public export`` 的类型和定义是导出的
+ ````public export`` 导出类型和定义
```

Re: 咱直接用了 xx 表示 xxx，因为前文说的是 xx 标记表示什么

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/modules.rst#L127

同L157

**Comment by fangyi-zhou** [comment]
https://github.com/Idris-zh/Idris-dev/blame/master/docs/tutorial/modules.rst#L403

https://en.wikipedia.org/wiki/Parameter_(computer_programming)
2 是 argument 此处注解有误
